node_js: 
- "0.10"
env: 
  matrix:
    secure: "ofToNCIFt9KhGsqioFh6wD5U4WbPOnjp+WL8ARrvwjZ+hpzouvIT13mKNg2YN+mM8buBZWO9c8iDBKJTE53/F2Ri1vL1ehTDZGc5UIqD9MeJKvy01z1DlEjiz9JhsIxVemXtH/mNafC92lfoAn9QprOEdRgCyYDBZf/WQ+GRTO0="
language: node_js
before_script: 
  - npm install -g bower grunt-cli
  - bower install
after_success:
  - grunt --force
  - git remote set-url --push origin https://github.com/gire/Ohtu1
  - git remote set-branches --add origin gh-pages
  - git fetch -q
  - git config user.name gire
  - git config user.email giire@hotmail.fi
  - git config credential.helper "store --file=.git/credentials"
  - echo https://$GH_TOKEN:@github.com > .git/credentials
  - git branch gh-pages origin/gh-pages
  - ./pages.sh
  - rm .git/credentials
