node_js: 
- "0.10"
env: 
  matrix:
    secure: "dqFg3We+roZV9bP0BPLipIinNdzAq0V5rRAr91GyZ4D59sdWnYlHhTm5XkSjevXCTnbzyumP6NXidCrjcdsyptUktfuHl95TPKkVv489cCe93kKoMRRwJi4Re9DarJIuq50FL7bDX6EUdc8+ZlODeS2ITAC4B6VIF7UR0TKolDA="
language: node_js
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script: 
  - npm install -g bower grunt-cli
  - bower install
after_success:
  - grunt build --force
  - git remote set-url --push origin https://github.com/kilhwch/Ohtu1
  - git remote set-branches --add origin gh-pages
  - git fetch -q
  - git config user.name gire
  - git config user.email giire@hotmail.fi
  - git config credential.helper "store --file=.git/credentials"
  - echo https://$GH_TOKEN:@github.com > .git/credentials
  - git branch gh-pages origin/gh-pages
  - ./pages.sh
  - rm .git/credentials

